import type { Metadata } from 'next';
import './globals.css';
import { Pretendard, nexonGothicBold, nexonGothicLight, nexonGothicRegular } from './font';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`
        ${Pretendard.className}
        ${Pretendard.variable}
        ${nexonGothicBold.variable}
        ${nexonGothicLight.variable}
        ${nexonGothicRegular.variable}
        antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
